name: Bazel CLI Build (macOS)

on:
  push:
    paths:
      - 'cli/**'
      - '.github/workflows/bazel_cli_build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cli/**'
      - '.github/workflows/bazel_cli_build.yml'
  workflow_dispatch:


jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Build CLI with Bazel
        run: bazel build //cli/...
      - name: Build Java Language Module
        run: bazel build //language/java/...
      - name: Build XML Language Module
        run: bazel build //language/xml/...
      - name: Build SQL Language Module
        run: bazel build //language/sql/...
      - name: Build JavaScript Language Module
        run: bazel build //language/javascript/...
      - name: Build Properties Language Module
        run: bazel build //language/properties/...
      - name: Build Python Extractor Module
        run: bazel build //language/python/...
      - name: Build ArkTS Language Module
        run: bazel build //language/arkts/...
      - name: Build Go Extractor Module
        run: bazel build //language/go/...
      - name: Build CFamily Extractor Module
        run: bazel build //language/cfamily/...
      - name: Build  All
        run: bazel build //...
